service: budgetcontrol-gateway # Replace with your microservice name
provider:
  name: aws
  region: eu-west-1
  runtime: provided.al2
  environment:
    APP_CONFIG: lambda
    APP_NAME: ${env:APP_NAME}
    APP_ENV: ${env:APP_ENV}
    APP_KEY: ${env:APP_KEY}
    LOG_CHANNEL: ${env:LOG_CHANNEL}
    LOG_LEVEL: ${env:LOG_LEVEL}
    QUERY_FILTERS: ${env:QUERY_FILTERS}
    API_SECRET: ${env:API_SECRET}
    WEBHOOK_SECRET: ${env:WEBHOOK_SECRET}
    CACHE_TTL: ${env:CACHE_TTL}
    CACHE_DRIVER: ${env:CACHE_DRIVER}
    DB_CONNECTION: ${env:DB_CONNECTION}
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_DATABASE: ${env:DB_DATABASE}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_COLLATION: ${env:DB_COLLATION}
    CACHE_REDIS_PASSWORD: ${env:CACHE_REDIS_PASSWORD}
    CACHE_REDIS_HOST: ${env:CACHE_REDIS_HOST}
    AWS_COGNITO_ACCESS_KEY_ID: ${env:AWS_COGNITO_ACCESS_KEY_ID}
    AWS_COGNITO_SECRET_ACCESS_KEY: ${env:AWS_COGNITO_SECRET_ACCESS_KEY}
    AWS_COGNITO_CLIENT_ID: ${env:AWS_COGNITO_CLIENT_ID}
    AWS_COGNITO_CLIENT_SECRET: ${env:AWS_COGNITO_CLIENT_SECRET}
    AWS_COGNITO_USER_POOL_ID: ${env:AWS_COGNITO_USER_POOL_ID}
    AWS_COGNITO_REGION: ${env:AWS_COGNITO_REGION}
    AWS_COGNITO_VERSION: ${env:AWS_COGNITO_VERSION}
    DYNAMODB_CACHE_TABLE: ${env:DYNAMODB_CACHE_TABLE}
    DYNAMODB_ENDPOINT: ${env:DYNAMODB_ENDPOINT}
    DYNAMODB_CACHE_KEY: ${env:DYNAMODB_CACHE_KEY}
    WORKSPACE_API_BASE_URL: ${env:WORKSPACE_API_BASE_URL}
    AUTH_API_BASE_URL: ${env:AUTH_API_BASE_URL}
    STATS_API_BASE_URL: ${env:STATS_API_BASE_URL}
    BUDGETS_API_BASE_URL: ${env:BUDGETS_API_BASE_URL}
    CORE_API_BASE_URL: ${env:CORE_API_BASE_URL}
    SEARCH_ENGINE_API_BASE_URL: ${env:SEARCH_ENGINE_API_BASE_URL}
    WALLET_API_BASE_URL: ${env:WALLET_API_BASE_URL}
    ENTRY_API_BASE_URL: ${env:ENTRY_API_BASE_URL}
    LABEL_API_BASE_URL: ${env:LABEL_API_BASE_URL}
    DEBT_API_BASE_URL: ${env:DEBT_API_BASE_URL}
    SAVINGS_API_BASE_URL: ${env:SAVINGS_API_BASE_URL}
    GOALS_API_BASE_URL: ${env:GOALS_API_BASE_URL}
  deploymentBucket:
    name: serverless-framework-deployments-eu-west-1-41d5edce-535f
plugins:
  - ./vendor/bref/bref
functions:
  web:
    handler: public/index.php
    layers:
      - arn:aws:lambda:eu-west-1:534081306603:layer:php-82-fpm:99
    events:
      - httpApi: '*'
package:
  exclude:
    - '.git/**'
    - '.idea/**'
    - 'node_modules/**'
    - 'tests/**'
    - 'storage/logs/**'
    - '.env'
    - '.env.*'
  include:
    - 'public/**'
    - 'vendor/**'
    - 'bootstrap/**'
    - 'storage/**'