version: '3'
dotenv:
  - ".env"
tasks:
  build:dev:
    desc: Build production enviroment
    cmds:
      - docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d
      - docker container cp bin/apache/default.conf budgetcontrol-gateway:/etc/apache2/sites-available/budgetcontrol.cloud.conf
      - docker container exec budgetcontrol-gateway service apache2 restart